// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import { Asset, Entry } from "contentful";
import { Document } from "@contentful/rich-text-types";

export interface IWorkoutProgramFields {
  /** Program Image */
  programImage?: Asset | undefined;

  /** Program Name */
  programName: string;

  /** Program Information */
  programInformation: Document;

  /** Program Assets */
  programAssets?: Asset[] | undefined;
}

export interface IWorkoutProgram extends Entry<IWorkoutProgramFields> {
  sys: {
    id: string;
    type: string;
    createdAt: string;
    updatedAt: string;
    locale: string;
    contentType: {
      sys: {
        id: "workoutProgram";
        linkType: "ContentType";
        type: "Link";
      };
    };
  };
}

export type CONTENT_TYPE = "workoutProgram";

export type IEntry = IWorkoutProgram;

export type LOCALE_CODE = "en-US";

export type CONTENTFUL_DEFAULT_LOCALE_CODE = "en-US";
